name: Tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Weekly.
    - cron: '0 0 * * 0'

jobs:
  test-generator:
    name: Test Generator
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Run generator tests
        run: crystal spec test-generator/spec/*
  test-generator-templates:
    name: Check Generator Templates
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Check generator templates tests
        run: ./bin/test_specs
  template:
    name: Check file formatting
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Run file formatting
        run: crystal ./bin/check-format.cr
  exercises:
    name: Check exercises Crystal ${{ matrix.crystal }}
    runs-on: ubuntu-22.04
    strategy:
      # Allows running the job multiple times with different configurations
      matrix:
        crystal: ["1.7", "1.8", "1.9", "1.10", "1.11.2"]
    container:
      image: crystallang/crystal:${{ matrix.crystal }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Install jq
        run: apt-get update && apt-get install -y jq
      - name: Run tests
        run: ./bin/test-exercises.sh
  exercises-windows:
    name: Check exercises Crystal on Windows
    runs-on: windows-2022
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: "1.11.1"
      - name: 'Setup jq'
        run: choco install jq
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Run tests
        run: ./bin/test-exercises.ps1
