name: Tests
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Weekly.
    - cron: '0 0 * * 0'

jobs:
  generator:
    name: Check Generator Templates
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Run generator tests
        run: ./bin/test_specs
  template:
    name: Check file formatting
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Run file formatting
        run: crystal ./bin/check-format.cr
  exercises:
    name: Check exercises crystal ${{ matrix.crystal }}
    runs-on: ubuntu-22.04
    strategy:
      # Allows running the job multiple times with different configurations
      matrix:
        crystal: [1.5, 1.6, 1.7, 1.8, 1.9.2]
    container:
      image: crystallang/crystal:${{ matrix.crystal }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - name: Install jq
        run: apt-get update && apt-get install -y jq
      - name: Run tests
        run: ./bin/test-exercises.sh
